export const colors = [
  "red",
  "deep-purple",
  "light-blue",
  "green",
  "yellow",
  "deep-orange",
  "grey",
  "pink",
  "indigo",
  "cyan",
  "light-green",
  "amber",
  "brown",
  "purple",
  "blue",
  "teal",
  "lime",
  "orange",
  "blue-grey",
  "red-darken-2",
  "deep-purple-darken-2",
  "light-blue-darken-2",
  "green-darken-2",
  "yellow-darken-2",
  "deep-orange-darken-2",
  "grey-darken-2",
  "pink-darken-2",
  "indigo-darken-2",
  "cyan-darken-2",
  "light-green-darken-2",
  "amber-darken-2",
  "brown-darken-2",
  "purple-darken-2",
  "blue-darken-2",
  "teal-darken-2",
  "lime-darken-2",
  "orange-darken-2",
  "blue-grey-darken-2",
]

// export enum colors {
//   red = "red",
//   deepPurple = "deep-purple",
//   lightBlue = "light-blue",
//   green = "green",
//   yellow = "yellow",
//   deepOrange = "deep-orange",
//   grey = "grey",
//   pink = "pink",
//   indigo = "indigo",
//   cyan = "cyan",
//   lightGreen = "light-green",
//   amber = "amber",
//   brown = "brown",
//   purple = "purple",
//   blue = "blue",
//   teal = "teal",
//   lime = "lime",
//   orange = "orange",
//   blueGrey = "blue-grey",
// }
